name: version-reminder

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}/${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

jobs:

  version-reminder:
    name: version-reminder
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions:
      pull-requests: write

    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: main

      - name: version-check
        id: version_check
        if: hashFiles('VERSION')
        run: |
          VERSION_FILE="VERSION"
          setOutput() {
            echo "${1}=${2}" >> "${GITHUB_OUTPUT}"
          }
          git fetch origin main
          if ! git diff --unified=0 origin/main.. -- $VERSION_FILE | grep '^[+-]' | grep -i "version" >/dev/null
          then
            echo "remind bumping"
            setOutput "remind" 'true'
          else
            echo "version is being BUMPED $(cat $VERSION_FILE)"
            setOutput "remind" 'false'
          fi

      - name: version-reminder-comment
        if: hashFiles('VERSION') && steps.version_check.outputs.remind == 'true'
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const backtick = '`';
            const body = `
            ### :bulb: **Don't forget to bump the VERSION file**

            By bumping the version in ${backtick}VERSION${backtick} file, we trigger a repo TAG and repo RELEASE, else nothing happens.
            `.trim();

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
